spring.application.name=orders

spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgrespassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Caffeine Cache Configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=5m
spring.cache.cache-names=productCategories,priceTypeDefault
