apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: orders-desk
  labels:
    app: orders-app
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/mydatabase"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_LIQUIBASE_CHANGE_LOG: "classpath:db/changelog/db.changelog-master.xml"
  SPRING_CACHE_TYPE: "caffeine"
  SPRING_CACHE_CAFFEINE_SPEC: "maximumSize=500,expireAfterWrite=5m"
  SPRING_CACHE_CACHE_NAMES: "productCategories,priceTypeDefault"

